import assert from 'node:assert/strict'
import { it } from 'node:test'

import * as solidark from './index.js'

it('index exports the public API', () => {
  assert.equal(typeof solidark.Component, 'function')
  assert.equal(typeof solidark.html, 'function')
  assert.equal(typeof solidark.camelCase, 'function')
  assert.equal(typeof solidark.parseAttributeValue, 'function')
  assert.equal(typeof solidark.parseVector, 'function')
  assert.equal(typeof solidark.stableStringify, 'function')
  assert.equal(typeof solidark.defineSolidarkElements, 'function')
  assert.equal(typeof solidark.SolidarkRuntime.evaluate, 'function')
  assert.equal(typeof solidark.parseTopologySelector, 'function')
  assert.equal(solidark.ViewerComponent.tag, 'sol-viewer')
  assert.equal(solidark.ColorComponent.tag, 'sol-color')
  assert.equal(typeof solidark.createViewer, 'function')
  assert.equal(typeof solidark.canUseThreeTarget, 'function')
  assert.equal(typeof solidark.createThreeCadScene, 'function')
  assert.equal(typeof solidark.ThreeCadRenderer, 'function')
  assert.equal(typeof solidark.createSceneSvg, 'function')
  assert.equal(typeof solidark.createMeshSceneSvg, 'function')
  assert.equal(typeof solidark.collectPrimitiveEntries, 'function')
  assert.equal(typeof solidark.collectMeshTriangles, 'function')
  assert.equal(typeof solidark.normalizeElement, 'function')
  assert.equal(typeof solidark.evaluateNode, 'function')
  assert.equal(typeof solidark.Kernel, 'function')
  assert.equal(typeof solidark.MemoryKernel, 'function')
  assert.equal(typeof solidark.OpencascadeKernel, 'function')
  assert.equal(typeof solidark.createInMemoryKernel, 'function')
  assert.equal(typeof solidark.constructOpenCascadeBinding, 'function')
  assert.equal(typeof solidark.createOpenCascadeAdapter, 'function')
  assert.equal(typeof solidark.createOpenCascadeKernel, 'function')
  assert.equal(typeof solidark.loadGlobalKernel, 'function')
  assert.equal(typeof solidark.useInMemoryKernel, 'function')
})
